### ISSUE TITLE
target type is int64 still raising error 

### ISSUE THREAD

**Issue by devrup-csv** [fbdesignpro/sweetviz#1]
63             if predetermined_type_target not in (FeatureType.TYPE_BOOL,
     64                                                  FeatureType.TYPE_NUM):
---> 65                 raise ValueError
     66             self.predetermined_type_target = predetermined_type_target
     67         else:

ValueError: 

this error raised in spite of target being 1,2,3 values and type being int64

**Comment by fbdesignpro** [comment]
Sweetviz only supports tracking targets that are of type NUMERICAL or BOOLEAN. This error would happen if you try something that has 3 values (it would get set as CATEGORICAL).

Commit a8529a458b9f111060fa20a767fdcbb4654f9425 (1.0alpha4) addresses this in 2 ways:

1. Better documentation of the error in the "raise" statement
2. Added support to force a categorical variable to be numerical, using the FeatureConfig setup.
