### ISSUE TITLE
Fail to allocate bitmap - Process finished with exit code -2147483645

### ISSUE THREAD

**Issue by jonathanecm** [fbdesignpro/sweetviz#111]
I am processing 4 datasets with different number of variables and each with over 4 million rows. When processing the 4 with 52 variables. I get this error and the Python console stops.

**Comment by fbdesignpro** [comment]
@jonathanecm this sounds potential he like a memory error (allocation?). I know it's been a while, but if you are still looking at that, were you able to successfully process smaller data sets?
