### ISSUE TITLE
It worked in Jupyter but it is not generating report in Google Colab:(

### ISSUE THREAD

**Issue by ShubhangiSoni1603** [fbdesignpro/sweetviz#12]

**Comment by fbdesignpro** [comment]
Hello @ShubhangiSoni1603, Thank you for the report! You're not the first report issues with Colab.

The report SHOULD be generated, it just not pops up in the notebook. It should be created in the filesystem. Have you looked at the files area of your notebook? e.g.

![image](https://user-images.githubusercontent.com/65080980/84391874-8e274000-abc7-11ea-8dd6-7586b9cf9b5f.png)

You should see the HTML report, download it and view it on your computer. I know it's not as integrated as it could be but I hope you will find it useful. I plan on adding a more integrated report, but I just need to find time. :) Either way, I will add a note in the readme for this.

Let me know if that works, or if it is not being treated at all.

Thanks again,

Francois

**Comment by ShubhangiSoni1603** [comment]
Thanks, sir!
This library helped me a lot.
