### ISSUE TITLE
Not reading overrrde.ini - to remove logo

### ISSUE THREAD

**Issue by thongfam** [fbdesignpro/sweetviz#120]
Hi,

I have tried to insert the line sv.config_parser.read("override.ini") into my code right after the import after I have set "show_logo = 0" under the layout section but I noticed it is still reading from the default .ini file as opposed to the new one (which I have duplicated from existing one before apply my change).

If I proceed to set the "show_logo = 0" in teh default ini file, it is working (logo no longer shows), Any advise?

Thanks.

**Comment by fbdesignpro** [comment]
@thongfam This should have been fixed, I know it's been forever but if this is still an issue let me know otherwise I will close..

**Comment by fbdesignpro** [comment]
Closing due to no further feedback
