### ISSUE TITLE
Add an argument to silence the progress bar

### ISSUE THREAD

**Issue by LexABzH** [fbdesignpro/sweetviz#124]
Is it possible to add an argument to silence the progress bar ?

We want to use SweetViz in an automatique pipeline and store the report in a database.
We already have a lot of logs in our process, hence we would love to get rid of the progress bar logs.
We can deactivate tqdm before loading SweetViz, but that would also impact others parts of our process.

One solution might be to add an argument in `DataframeReport.__init__` and set `self.progress_bar` to a fake logger.

**Comment by fbdesignpro** [comment]
Added in 2.3.0, thanks again @LexABzH!

**Comment by LexABzH** [comment]
Thanks, I will try it :)

**Comment by fbdesignpro** [comment]
@LexABzH awesome, let me know if there are any issues with it!
