### ISSUE TITLE
sweetviz libaray

### ISSUE THREAD

**Issue by aishwaryarajendragulve** [fbdesignpro/sweetviz#13]
Hi,
I am not able to install sweetviz library. It Installed in the anaconda prompt but not working in the Jupyter notebook.

**Comment by fbdesignpro** [comment]
Hi! If it is installed in the same environment/venv as the notebook, it should work. So you are not able to import it at all from the project? Do you see it if you run `pip list`? Thank you!

**Comment by fbdesignpro** [comment]
Closing as no answer was provided and system seems to be working in other similar setups.
