### ISSUE TITLE
module 'numpy' has no attribute 'warnings' AttributeError with numpy > 1.23.x

### ISSUE THREAD

**Issue by katiesandford** [fbdesignpro/sweetviz#130]
Bug:
Given I have installed numpy 1.24 and sweetviz 2.1.4 (the latest)
When I call any sweetviz function which instantiates a GraphNumeric class
The code throws: `AttributeError: module 'numpy' has no attribute 'warnings' 

Expected:
Either sweetviz pins numpy to <1.24 where np.warnings existed
Or ideally,
graph_numeric is made to work with the latest numpy

Here is a log of the error on mac (monterey with m1 chip) and python3.10. The graph numeric class calls np.warnings (https://github.com/fbdesignpro/sweetviz/blob/master/sweetviz/graph_numeric.py), which works for 1.23.x, but was removed in 1.24. I cannot find the removal in the numpy release notes, but it definitely seems to have been removed.

<img width="1356" alt="Screenshot 2023-01-05 at 10 30 21" src="https://user-images.githubusercontent.com/6432100/210766568-e444af94-bd05-4112-a046-fcadfa4d9f72.png">

**Comment by fbdesignpro** [comment]
The next release will contain the fix.
