### ISSUE TITLE
How to show chinese in ASSOCIATIONS

### ISSUE THREAD

**Issue by nealcha** [fbdesignpro/sweetviz#138]
Hi,I have just tried to use sweetviz to do EDA. And I have a problem that in ASSOCIATIONS it doesn't support chinese, and I got this:
![Uploading image.png…]()
Is there anything I can do to solve it?Thanks!

**Comment by nealcha** [comment]
modifying the config file is ok

**Comment by fbdesignpro** [comment]
I will take it configuring to use CJK resolved the issue. Please post again if there are still issues and I will update. Thank you!
