### ISSUE TITLE
what does the size of circle in ASSOCIATIONS mean？

### ISSUE THREAD

**Issue by nealcha** [fbdesignpro/sweetviz#139]
Hi，I am using sweetviz to analysis the correlation between data. I know in ASSOCIATIONS map the color means Pearson's coef, and I am wondering what the different sizes of circle in ASSOCIATIONS mean for?THANK YOU!

**Comment by fbdesignpro** [comment]
@nealcha The size should be proportional to the coefficient as well, as an added visual cue
