### ISSUE TITLE
Mixed Data Type issue

### ISSUE THREAD

**Issue by v-rao** [fbdesignpro/sweetviz#14]
@fbdesignpro 

I was working on the online retail dataset.

![Screenshot (597)](https://user-images.githubusercontent.com/40270731/85914845-c1243180-b85f-11ea-93ba-22b960239a2d.png)

In this dataset, the variable 'Invoice Number' is a 6-digit integral number uniquely assigned to each transaction. If this code starts with the letter 'C', it indicates a Cancellation.

And once I run the following code I get the error below:

![Screenshot (598)](https://user-images.githubusercontent.com/40270731/85914852-d4370180-b85f-11ea-99a9-52fc8457f1b6.png)

**Comment by a246530** [comment]
It states in the error code that you can't use a mixed type like you described above. As a work around for now, you could pull the 'c' out of that field and move it to its own field.

**Comment by v-rao** [comment]
> It states in the error code that you can't use a mixed type like you described above. As a work around for now, you could pull the 'c' out of that field and move it to its own field.

Can't do that because Invoice Number is a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter 'C', it indicates a Cancellation.

**Comment by fbdesignpro** [comment]
@v-rao sorry for the delay I was not able to respond for the past few days. Can you explicitly convert the column to be text (e.g. "object" type)? This should get rid of the issue. 

I believe newer versions of the library have added a more verbose error message.

**Comment by fbdesignpro** [comment]
Closing as this is as per documented; mixed type cannot be supported.
