### ISSUE TITLE
sweetviz installed but won't run: module 'numpy' has no attribute 'warnings'

### ISSUE THREAD

**Issue by madisondevin** [fbdesignpro/sweetviz#146]
Sweetviz is installed, version  2.1.4   (on Windows)
![image](https://github.com/fbdesignpro/sweetviz/assets/58914963/a9765512-57c2-4450-840f-dcf3d5da933e)

But when I try to use it I get an error
![image](https://github.com/fbdesignpro/sweetviz/assets/58914963/9e12538a-d49f-4fa8-b508-1d3776128295)

Numpy version is 
numpy                     1.24.3          py311hdab7c0b_1
numpy-base                1.24.3          py311hd01c5d8_1

I tried downgrading numpy as per a previous post, but it impacts other packages that I need. Please advise, thanks!

**Comment by frank1010111** [comment]
You can avoid having to downgrade numpy with this fix: https://github.com/fbdesignpro/sweetviz/pull/131#issuecomment-1401394461

**Comment by fbdesignpro** [comment]
@madisondevin @frank1010111 I am currently on break for the next few days but will be investigating this upon my return, hopefully we can fix this quickly.

**Comment by fbdesignpro** [comment]
Thanks again for reporting this, should be fixed with the latest version 2.2.1! Please let us know if you run into anything else with the latest version.
