### ISSUE TITLE
show_html() doesn't shows the output jupyter notebook / lab 

### ISSUE THREAD

**Issue by Christophe-pere** [fbdesignpro/sweetviz#15]
Hi there,

I try to use sweetviz in local: 

- Ubuntu 20.04 

And in anaconda enterprise:

- K8s with centOS

Both lead to the same issue. The display of the output in jupyter lab and notebook isn't visible. 

Local:
- Jupyter_lab=2.0 
AE:
- jupyter=1.0.0
- jupyter_client=5.3.3
- jupyter_console=6.0.0
- jupyter_core=4.5.0
- Jupyter_lab=1.1.3
- ipython=7.8.0

The report has been generated but not display. 

How to fix it? 

Best

**Comment by a246530** [comment]
So it does save the file but it doesn't automatically open it in the web browser on these systems correct? When you open that HTML file it saves, it opens correctly though?

**Comment by Christophe-pere** [comment]
Yes, the report is correctly saved, it can be open in a browser, but, working on anaconda enterprise I want to see the result in widget. Without this, the library lost a big potential application.

**Comment by kais-viz** [comment]
I can confirm the same on kaggle, the html is produced correctly but doesn't open in the editor.

**Comment by a246530** [comment]
#25 should take care of this I think. I have not tested yet.

**Comment by shgo** [comment]
Hey folks, giving my two cents on this, I miss a method that is able to generate the html output without opening it in a browser.
Is there such a way to use sweetviz? If not, do you think it would be useful to have a new method that only generates the html output without showing it? Or maybe an argument on show_html?

**Comment by fbdesignpro** [comment]
@shgo Thank you for the feedback; this has been suggested a few times and is the very next thing I will implement.

To better implement the feature, I was wondering how you would be using this HTML. I am guessing you would Incorporate it into Another page so you would NOT want <head> and <body> tags, correct? 

Thank you, any info will help implement the feature in a way that works best!

**Comment by shgo** [comment]
In my case, I want to generate a set of reports programmatically, with the html output being stored in another folder to be visualized later on as reports.

**Comment by fbdesignpro** [comment]
@shgo Thank you for the information, this will get added in the next update.
