### ISSUE TITLE
Deprecation warning while importing `display()` (Sweetviz 2.2.1)

### ISSUE THREAD

**Issue by GegznaV** [fbdesignpro/sweetviz#156]
Sweetviz 2.2.1 gives several deprecation warnings. One of them:

- [ ] Importing `display` from `IPython.core.display` is deprecated since IPython 7.14, please import from IPython display 

Details:

```
[c:\Users\user\anaconda3\envs\env\Lib\site-packages\sweetviz\dataframe_report.py:580](file:///C:/Users/user/anaconda3/envs/env/Lib/site-packages/sweetviz/dataframe_report.py:580): DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display
```

**Comment by fbdesignpro** [comment]
@GegznaV thanks for the heads up! I was not seeing it on my test bench running the library, but I'm sure it shows up in Jupyter. I'm on a new machine so I will set that up. The workaround is easy enough but I do want to have a before/after test case.
