### ISSUE TITLE
Import library without installing it

### ISSUE THREAD

**Issue by ankita2020** [fbdesignpro/sweetviz#159]
I downloaded the source code  from sweetviz's GitHub and my project directory was like this --
my_project/
├── sweetviz/
│   ├── __init__.py
│   ├── ...
├── my_script.py

The issue is that when I import this library( in my_script.py and run the file) without installing it gives **importlib.metadata.PackageNotFoundError: sweetviz** on the terminal and gives PackageNotFoundError: sweetviz on jupyter notebook . I also did  -

import sys
sys.path.append("D:\Download\my_project\sweetviz")

So it is possible to import this library without installing it? If yes then tell me what would  I have to do and whatever I did was correct or wrong.
Please solve this query ASAP.

Thanks in advance...

**Comment by fbdesignpro** [comment]
@ankita2020 apologies for the slight delay in answering. I used your code and it should work, but you need to NOT include "sweetviz" in the path, as it is what the `import` commanders looking for. Here is what I ran in Jupyter: 
(You may also change your `\` to `/`, as it might mess the string up unless it is a raw string, although it seemed to work without any changes)
![image](https://github.com/fbdesignpro/sweetviz/assets/65080980/58dfd4d8-9fd2-4f97-aea9-d8e4d16564e2)
