### ISSUE TITLE
Larger feature visualization on right is hidden

### ISSUE THREAD

**Issue by JohnDeJesus22** [fbdesignpro/sweetviz#17]
Appreciate the effort for this library and I see the potential!. Tried out at work and when the html displayed the charts for features are partially hidden. Thought that I could scroll over to see them but no horizontal scroll bar was available.

**Comment by Sohaibe93** [comment]
Hello, until this problem of scrolling horizontally is solved, you can inspect the element of your html in your browser and set `overflow-x` parameter to `visible` instead of `hidden` which will permits you to have a horizontal scrolling bar.

**Comment by fbdesignpro** [comment]
@JohnDeJesus22 @Sohaibe93 Thank you for taking the time to submit this! 

Ironically, I originally had a scrollbar but to make "everything fit" as tightly as possible I got rid of it. I will bring it back in the next version because that was overkill for a dumb cosmetic consideration and ends up being much worse than the original problem!

I will close this when the fix is submitted, hopefully pretty soon! Thanks again!

**Comment by fbdesignpro** [comment]
@JohnDeJesus22 @Sohaibe93 The horizontal scroll bar is now back in 1.0beta3! Can you let me know if this is now working on your end? Sometimes updates have had issues being applied so I just wanted to make sure. :)

**Comment by JohnDeJesus22** [comment]
@fbdesignpro Thanks for the quick update on this! It is working well. I can scroll horizontally now. It is cool seeing the correlation associations for features!

Question: When you get those charts and tables for a selected feature, are they suppose to fit to screen? On 100% view they are vertically cut off but if I zoom out I can see them.

Thanks again for the help and this awesome library!

**Comment by Sohaibe93** [comment]
@fbdesignpro Thank you, it works great now :)

**Comment by fbdesignpro** [comment]
@JohnDeJesus22 Glad to hear it! The display was made to fit on a 1080p screen, so if your monitor is smaller it would be cut off. I'm glad zooming out does solve it but out of curiosity what resolution/platform are you using?
