### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Pini79** [fbdesignpro/sweetviz#20]
Hi, the execution throws the "Zero Division Error".
I'm new with Jupiter Notebook and Python.

C:\Anaconda3\lib\site-packages\sweetviz\graph_associations.py in heatmap(y, x, figure_size, **kwargs)
    224 
    225     # Scale with num squares
--> 226     size_scale = size_scale / len(x)
    227     def value_to_size(val):
    228         if size_min == size_max:

ZeroDivisionError: float division by zero

Thanks a lot!
Luciano.-

**Comment by Pini79** [comment]
The dataset contains the following structure:

IDSUSCRIPCION	IDCONTRIBUYENTE	IDSERVICIO	FECHA_SUSCRIPCION	HABILITADA	ORIGEN
6047184	2309304	BEInmo	2019	S	W  
6047185	2309305	BEAuto	2019	S	W  
6047186	2309306	BEAuto	2019	S	W  
6047187	1302989	BEInmo	2019	S	W

**Comment by fbdesignpro** [comment]
@Pini79 Thank you for submitting this, I will look into this!

**Comment by fbdesignpro** [comment]
@Pini79 this should be resolved with the latest version (1.0beta3), can you verify this is fixed for you? I will mark this is close if that is the case. Thank you!
