### ISSUE TITLE
issue on profile on date field

### ISSUE THREAD

**Issue by nirmalyachoudhuri** [fbdesignpro/sweetviz#25]
File "c:\users\appdata\local\programs\python\python37\lib\site-packages\pandas\core\base.py", line 1220, in _reduce
    klass=self.__class__.__name__, op=name

TypeError: DatetimeIndex cannot perform the operation sum

**Comment by fbdesignpro** [comment]
@nirmalyachoudhuri thank you for submitting this! We are looking into #22 to fix this and will keep you posted!

**Comment by fbdesignpro** [comment]
Should be fixed with the latest commits, I will close this when a formal `pip` build is sent out!

**Comment by fbdesignpro** [comment]
Closing, issue should be resolved in 1.0a8!
