### ISSUE TITLE
Unable to compare the loan prediction dataset

### ISSUE THREAD

**Issue by nishantp95** [fbdesignpro/sweetviz#28]
I get an error as :
TypeError: cannot do label indexing on <class 'pandas.core.indexes.numeric.Int64Index'> with these indexers [16.12000084] of <class 'float'>

when trying to compare the train and test dataset for loan prediction.
The code I have written is : 
my_report = sv.compare([df_train,"Train"],[df_test,"Test"],"Loan_Status")

**Comment by fbdesignpro** [comment]
@nishantp95 thank you for taking the time to report this!

I will look into this and see if some of our current upcoming fixes would fix this. There are a bunch of these loan data sets out there, is this a public data set, and if so can you put a link here? I will make sure to test that set.

**Comment by nishantp95** [comment]
@fbdesignpro the link for the dataset is as below :
https://datahack.analyticsvidhya.com/contest/practice-problem-loan-prediction-iii/#ProblemStatement

**Comment by fbdesignpro** [comment]
@nishantp95 Thank you, I will investigate!

**Comment by fbdesignpro** [comment]
@nishantp95 just pushed a fix! Thanks again! Will include in next version on `pip`.

**Comment by fbdesignpro** [comment]
Closing, issue should be resolved in 1.0a8
