### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute 'style'

### ISSUE THREAD

**Issue by kishoremarodia** [fbdesignpro/sweetviz#34]
File "C:\...\Python\Python37\site-packages\sweetviz\graph.py", line 58, in set_style
    matplotlib.style.use(styles_in_final_location)

AttributeError: module 'matplotlib' has no attribute 'style'

**Comment by vidyap-xgboost** [comment]
@kishoremarodia can you edit and paste your entire code here to get a better understanding and may be to reproduce it? 

What is the system you're working on?

**Comment by fbdesignpro** [comment]
It does look like a version/install/environment issue.
