### ISSUE TITLE
Add version attribute __version__

### ISSUE THREAD

**Issue by bhishanpdl** [fbdesignpro/sweetviz#41]
This is just a suggestion to the developer of this awesome module:

Generally to get the version number of a python module we do:
```python
import numpy

numpy.__version__ 

The dunder method   __version__ gives the version number.
```

I suggest to add this attribute to this library so that this gives the version number:

```python
import sweetviz

print(sweetviz.__version__)
```

**Comment by fbdesignpro** [comment]
@bhishanpdl good suggestion, will do! Thank you! :)

**Comment by fbdesignpro** [comment]
Thank you, added in the latest 1.0beta4!
