### ISSUE TITLE
Make font color of "missing" red

### ISSUE THREAD

**Issue by bhishanpdl** [fbdesignpro/sweetviz#43]
Suggestion:

This is an open suggestion that the font color of "missing" in report HTML would be nicer (IMHO) it has color red.

**Comment by fbdesignpro** [comment]
@bhishanpdl thank you for the suggestion! This totally makes sense to us; actually our original design had "Missing" field had a color-coded rectangular highlight, we just never got around to implementing it.

This is simple enough and it's good to see that was something that would be appreciated so we will increase the priority.

**Comment by a246530** [comment]
I gotta plus one this. Red would be nice. Sometimes i miss the blue part because it blends in.

**Comment by fbdesignpro** [comment]
@bhishanpdl and @a246530, thank you for your feedback, you will be happy to know that version 1.1 includes this feature and really helps point out the level of missing data in features.

If you have a chance to try it out, do let me know how it works for you.

Either way, thank you!

Francois

**Comment by fbdesignpro** [comment]
Updated as of 1.1
