### ISSUE TITLE
Add more descriptive statistics

### ISSUE THREAD

**Issue by bhishanpdl** [fbdesignpro/sweetviz#44]
Some suggestions:
- There is already distinct count.

More features:
- number of ZEROS and its percentage

**Comment by fbdesignpro** [comment]
@bhishanpdl Thank you for the suggestion, should be easy enough to add!

**Comment by fbdesignpro** [comment]
@bhishanpdl thank you for the suggestion, this is now committed as part of version 2.0.9!

**Comment by bhishanpdl** [comment]
@fbdesignpro It's great that the feature is added.
The feature "number of Zeros" and its percentage is really helpful for binay features. For example, if there is 100% zeroes for a feature. It has only one unique values and it is worthless in modelling.
