### ISSUE TITLE
Sweetviz needs to handle None values in the missing values section

### ISSUE THREAD

**Issue by AarthiKalyanasundaram** [fbdesignpro/sweetviz#47]

**Comment by shgo** [comment]
Later on I'll prepare some steps for reproduction, but I also have noticed some irregular behavior when comparing datasets and one of them has a column with null values, which is expected to happen in this application.

Do you guys have some references explaining how to handle null values with more care in sweetviz (or other libs behind it)?

**Comment by AarthiKalyanasundaram** [comment]
@shgo , Do I need to add steps to reproduce or kind of references ?

**Comment by fbdesignpro** [comment]
@AarthiKalyanasundaram @shgo Thank you for the reports! I recently realized that I have not verified behavior enough with missing values, but you are correct it should definitely be handled. This is indeed why we are calling this a beta. :)

The latest (beta3) was the first to more meaningfully handle missing values. I know it has some issues still, but it was a stopgap to at least stop crashing and give some basic functionality. I would make sure that you are running that version (you can tell in the top left of the report with the logo), but I think it's likely you have found some other issues with it. Definitely post any steps to reproduce if you are able to, that will be greatly appreciated! I want to fix these ASAP (although as I mentioned in another post I am drowning in work at work in the moment, so it may take a few more days).

Thanks again for taking the time to report; I want the library to be as useful and solid as possible!

**Comment by shgo** [comment]
I am endorsing your question with some of the things I could notice.
But I think it would be great for everyone if you provide more details to reproduce what you mean. It is usually half of the way of finding a fix

**Comment by fbdesignpro** [comment]
@AarthiKalyanasundaram yes, any further information/replication steps would be extremely useful. Also, if you can confirm which version of Sweetviz you are using, just to be sure. Thank you!

**Comment by AarthiKalyanasundaram** [comment]
Hi,
I have attached my code file and word document with screenshots for replication.
![image](https://user-images.githubusercontent.com/36664362/88383924-156ff200-cdc9-11ea-82a3-40d426c19fde.png)
Both the Income and Age contains missing values but it is not represented in the html report.

I have attached the link (url) for the data used which contains None values as Missing data.

[https://raw.githubusercontent.com/AarthiKalyanasundaram/SweetViz_Library/master/Patient_Profile.csv](url)

**Comment by fbdesignpro** [comment]
Hello @AarthiKalyanasundaram, thank you for the detailed report!

I see what is happening; the issue is that the values are not missing, they are actual text saying "None". There are formal Pandas/Python/numpy representations of missing data (e.g. None, np.nan, etc), and it is what the library is looking for. I believe it is correct that way, because it's a well-understood built-in mechanism, and parsing text is a lot more unpredictable and could run into unforeseen consequences.

An easy way to fix this is to replace the text with the actual missing data representation:

`df = df.replace('None', np.nan)`

Let me know if that works, and thanks again!
