### ISSUE TITLE
Error message in pip install sweetviz

### ISSUE THREAD

**Issue by AngShengJun** [fbdesignpro/sweetviz#49]
Hi, attempting to install sweetviz using pip install sweetviz, but kept encountering following error message (reproduced below)
Am using pandas version 1.0.1. Kindly advise, thanks.

`Installing collected packages: importlib-resources, pandas, tqdm, sweetviz
  Attempting uninstall: pandas
    Found existing installation: pandas 1.0.1
    Uninstalling pandas-1.0.1:
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\users\\65943\\anaconda3\\lib\\site-packages\\~andas\\_libs\\algos.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.`

**Comment by a246530** [comment]
Do you have issues installing other packages. It appears to be a permissions error.

**Comment by anirbansaha96** [comment]
Please try `pip install sweetviz --user`. You're having an issue related to permissions.

**Comment by AngShengJun** [comment]
Hi, running `!pip install sweetviz` in jupyter notebook worked. Thanks for the prompt clarification!

**Comment by anirbansaha96** [comment]
Glad it helped. Have a nice day :) 👍

**Comment by fbdesignpro** [comment]
@anirbansaha96 thanks for jumping in with this excellent suggestion! :) 👍

**Comment by anirbansaha96** [comment]
@fbdesignpro Glad I could help. It's a great library. Waiting for branch #11 to be merged.
