### ISSUE TITLE
Time series plotting

### ISSUE THREAD

**Issue by onkarkhedkar** [fbdesignpro/sweetviz#5]

**Comment by onkarkhedkar** [comment]
I tried to analyze a categorical feature against the date provided in the data,even after changing the dtype of variable I was not able to plot for that specific column. Thanks

**Comment by fbdesignpro** [comment]
Hi! Thank you for the question! To be certain I understand; you are trying to use one variable as the target, correct? Also is that target the categorical data or is it the date? If the date is the target, it should be in a numerical format. (E.g. convert to days or something like that)

As another note, for now the only target values allowed are boolean and numerical.

I hope this helps, let me know if I can help in any other way.

**Comment by fbdesignpro** [comment]
Closing as 7c3a754 should fix categorical data, and this was mentioned as the main issue. I am making a note for further date/time support, though. :)
