### ISSUE TITLE
Incorrect report

### ISSUE THREAD

**Issue by RafeyIqbalRahman** [fbdesignpro/sweetviz#53]
The Sweetviz data analysis report is incorrect in my case.

The report in PDF format: [Analyst.html.pdf](https://github.com/fbdesignpro/sweetviz/files/5047620/Analyst.html.pdf)

Code to reproduce the error:

`from pandas import read_csv, DataFrame`
`!pip install sweetviz`
`import sweetviz as sv`
`df = read_csv('https://raw.githubusercontent.com/wanderloop/WanderlustAI/master/assumed_pha_thousand.csv',
                         low_memory=True,)`
`keep_cols = 'long lat MID_POINT_X'.split()`
`df = df.loc[:, keep_cols]`
`df.rename(columns={'MID_POINT_X': 'MPX',},
          inplace=True,)`
`keep_cols = 'long lat MPX'.split()`
`data_analyst_report = sv.analyze(df)`
`data_analyst_report.show_html('Analyst.html')`

**Comment by fbdesignpro** [comment]
Hi @RafeyIqbalRahman thank you for the report! This is due to an extremely small range of values, this will be fixed shortly, I will post back here when it is.

**Comment by RafeyIqbalRahman** [comment]
You're welcome.

**Comment by fbdesignpro** [comment]
@RafeyIqbalRahman just committed a fix. The main `pip` package will be updated later today and I will be posting here. When it is ready, remember to UNINSTALL then INSTALL to update. :) For some reason, simply doing `pip update` doesn't always work correctly.

**Comment by fbdesignpro** [comment]
@RafeyIqbalRahman 1.0b6 is now live, the issue should be fixed! If you have the opportunity, definitely let me know if it works or not and I will close the issue if it does. Thanks again!

**Comment by RafeyIqbalRahman** [comment]
Yes @fbdesignpro, the issue is fixed now. Thanks for the quick fix. I shall close the issue now. You're welcome. :)
