### ISSUE TITLE
AttributeError: module 'sweetviz' has no attribute 'analyze' in office network

### ISSUE THREAD

**Issue by mojo46** [fbdesignpro/sweetviz#55]
when i tried to analyze my data frame i am getting this error.

---->1 **my_report = sv.analyze(df)**
      2  my_report.show_html()

**Comment by mojo46** [comment]
when connected to a VPN like office network getting the above attribute error.

Do we have any solution for this ?

**Comment by fbdesignpro** [comment]
Hello @mojo46, thank you for your report. This type of error has been a bit mysterious to me as it would mean the install didn't work but it's not clear to me how. It looks like you close the issue. Can you tell me how we were able to resolve it if that's the case?

Thanks again!
