### ISSUE TITLE
Config File Not Applying Changes

### ISSUE THREAD

**Issue by Buckeyes2019** [fbdesignpro/sweetviz#57]
This is a great package and I love the idea of a one-stop data profile approach.  My only note is that I cannot seem to get the config file (sweet_viz.ini) to apply my changes.  I tried directing to my own .ini file with minor changes to sweet_vix.ini and the changes did not take.  I then tried changing the setting within sweet_viz.ini directly (by setting the logo =0) and it still did not take.  I used the code from the front page:   sv.config_parser.read("Override.ini")

Perhaps there is an example notebook that has used this successfully that could be shared?

**Comment by fbdesignpro** [comment]
@Buckeyes2019 thank you for the good words! I have not heard of something like this but it could be related to being used in the context of a notebook (file path or access?). I have not had time to look into things recently but I will add this to my priority list when I get back to it. The fact that changing the file itself didn't do anything is strange indeed.

**Comment by fbdesignpro** [comment]
@Buckeyes2019 Can you tell me the environment you are running in? (IDE, notebook type, etc. + Python version) Thank you!

**Comment by Buckeyes2019** [comment]
Jupyterlab 2.2.6
Python 3.8.5
SweetViz 1.0b6

**Comment by fbdesignpro** [comment]
Hello @Buckeyes2019!  Again, thank you for the report. I just updated Sweetviz to version 1.1, which should fix the issue. I don't know if you're still looking at the data, but it would be great if you could confirm this has fixed it.

Thanks again!
Francois

**Comment by fbdesignpro** [comment]
@Buckeyes2019 I am not sure if you're still getting this, but I will be closing this issue, as this should be fixed under 1.1, let me know if it still occurring! Thank you!
