### ISSUE TITLE
TypeError: conversion from numpy.float32 to Decimal is not supported

### ISSUE THREAD

**Issue by seantma** [fbdesignpro/sweetviz#58]
Hi, was running `compare_intra()` on my dataframe and encountered this error:

> TypeError: conversion from numpy.float32 to Decimal is not supported

>lib/python3.7/site-packages/sweetviz/sv_html_formatters.py in fmt_smart(value)
>     47         return "0.00"
>     48     elif absolute < 0.001:
>---> 49         return f"{Decimal(value):.2e}"
>     50     elif absolute < 0.1:
>     51         return f"{value:.3f}"

Should the `value` be converted into a Python item first?

**Comment by fbdesignpro** [comment]
@seantma thank you for the report! I wonder if we shouldn't do something like `Decimal(float(value))`. I cannot test this right away but if you are using sources you could try that, otherwise I will definitely give this a shot next week. Do you have a small sample error test case dataset just to be sure?

**Comment by fbdesignpro** [comment]
Just wanted to mention I've been buried with work but this is still on my radar as soon as I have a few minutes to Look into this! @seantma as I was saying it would always help if you had a small test case I could look at.  Thank you!

**Comment by fbdesignpro** [comment]
Hi @seantma! Again, thank you for the report. I just updated Sweetviz to version 1.1, which should fix the issue. I don't know if you're still looking at the data, but if you have a chance it would be great if you confirm this is now fixed.

Thanks again!
Francois

**Comment by fbdesignpro** [comment]
Closing, as this should be fixed under 1.1
