### ISSUE TITLE
show the value in  Continuous  grouping

### ISSUE THREAD

**Issue by lyj1991** [fbdesignpro/sweetviz#59]
Hello, 
1、when I deal with continuous variables, no matter whether I choose different groups of 5, 10 or 20, the range value of each group on the horizontal axis is not clear, and it is basically the same.
![image](https://user-images.githubusercontent.com/20986633/93587158-062daf00-f9dc-11ea-9977-35c017c26211.png)

![image](https://user-images.githubusercontent.com/20986633/93587015-c9fa4e80-f9db-11ea-9083-d3c18bd4e3e2.png)

2、Categorical variable graph cannot be rotated

**Comment by fbdesignpro** [comment]
@lyj1991 Thank you for the feedback! Apologies for the delay as I have been extremely busy at work.

1. The scale at the bottom doesn't change on purpose; the numbers at the bottom are not mapped to columns ("bins") 1:1, They simply indicate the location of the center of each bin. So looking at the same data the numbers at the bottom would not be expected to change, just that you get more detail as to the distribution. The reason to do this is to keep things consistent as there would not be enough room to put so many numbers at the bottom at higher number of subdivisions.

2. Categorical and numerical variables use different orientations on purpose to easily differentiate them, as well as have more room to display longer names horizontally for categorical data.

I hope this answers your questions, and always do not hesitate to post here if you have any questions or suggestions. Thank you!
