### ISSUE TITLE
colname is ‘index’  error

### ISSUE THREAD

**Issue by guduxingzou** [fbdesignpro/sweetviz#60]
if dataframe colname include 'index'  ,then you  will get error:

 the true value of a series is amabiguous. use a empty,a.bool(),a.item(),a.any() or a.all

so  delete or skip  'index' col.
列名里不能有叫index的列，否则会报错。要么直接删除，要么加到skip中即可。

**Comment by fbdesignpro** [comment]
@guduxingzou thank you for the report, good catch! I will look into this.

**Comment by fbdesignpro** [comment]
Hi @guduxingzou! Again, thank you for the report. I just updated Sweetviz to version 1.1, which should fix the issue. Can you confirm it is working better now? 

Thanks again!
Francois

**Comment by fbdesignpro** [comment]
Closing, as this should be fixed under 1.1
