### ISSUE TITLE
show_html Generate a Strange Layout of Analysis

### ISSUE THREAD

**Issue by HaoVJiang** [fbdesignpro/sweetviz#64]
Hey there, this is a great package and it is pretty handy. However, I run into a strange layout issue when generating the plot. 

> sweet = stz.analyze(data)
> sweet.show_html()

Above is the code I used, and I attached the result's layout as a png file below. 

1: Would you kindly inform me of the option for layout in show_html()?
2: How I should solve this issue? 

Thank you so much! 

![SWEETVIZ_REPORT-html](https://user-images.githubusercontent.com/62689377/96348964-7b8fac80-107a-11eb-99f9-e300def7d269.png)

**Comment by fbdesignpro** [comment]
Hi @HaoVJiang , thank you for posting here! I have never seen this output before. Are you installing from pip, or did you download the repository?

Also, could you upload the html report here, or email it to me privately? I wonder if it is browser related (which browser are you using?) or something with how the report was generated for some reason.

Thanks again!
Francois

**Comment by HaoVJiang** [comment]
Dear @fbdesignpro 

I hope this message finds you well. Thank you for your reply! and I think I installed the package correctly. Also, the browser I use is Chrome, and the ide I use is Pycharm. 

I attached the report in this post for your reference, and I am looking forward to hearing from you soon! 

[html report](file:///Users/jianghao/Downloads/report.html)

Best Wishes,
Sincerely Hao Jiang

**Comment by HaoVJiang** [comment]
file:///Users/jianghao/Downloads/report.html

**Comment by HaoVJiang** [comment]
Also, if you cannot access the link above, would you kindly provide your email address. So I can send the HTML file to you? Thank you again!

**Comment by fbdesignpro** [comment]
@HaoVJiang thank you; as you suspected the report link is not valid. Please send me the report to fb@fbdesignpro.com 

Also, are you getting this with any data set? Or only this one in particular?

Also, can you tell me what your development environment is? (Python version, IDE, etc.)

**Comment by HaoVJiang** [comment]
Hey Mr. Bertand, I sent the dataset and report link to the email address you provided. In addition, the IDE I am using is Python 3.7 Pycharm. Please let me know if you need anything from me! I hope you have a great weekend ahead!

**Comment by fbdesignpro** [comment]
@HaoVJiang thank you again; I could not reproduce the issue locally, even with your data set. I have not received a response to my e-mail from October 26, let me know if the issue is still happening with the latest version!
