### ISSUE TITLE
Sweetviz 2.0.1 updates

### ISSUE THREAD

**Issue by fbdesignpro** [fbdesignpro/sweetviz#67]
Hello @nathancarter @a246530 @bonamprabhu @chadaeschliman! I'm not sure what is the "proper" way to do this but since you guys are the most active collaborators, I thought I would ping you here regarding the new version of Sweetviz I just pushed. Most significantly, it has major updates with regard to reports:

- a new show_notebook(...) function to embed the output inside notebooks
- vertical layout
- scaling factor

I don't know if you're still actively using it but if you are, let me know if you run into any issues with these new features that may have slipped by the testing (especially with notebooks, whose environments may be very different). Cheers!

**Comment by nathancarter** [comment]
Congrats on the new release!  I'm finishing up a semester here, so no time at the moment to dive in, but the new features sound cool!  Looking forward to trying them out in the future.
