### ISSUE TITLE
library installing issues

### ISSUE THREAD

**Issue by Leocontreas** [fbdesignpro/sweetviz#7]
I cannot use the command "pip install sweetviz" since it gives me back an error message ("ERROR: Could not find a version that satisfies the requirement sweetviz (from versions: none)
ERROR: No matching distribution found for sweetviz"). 

So I tried to use the command "git clone https://github.com/fbdesignpro/sweetviz.git ", and it worked out, but when I import the library in python interpreter it seems sweetviz does not have any module I can use. Am I doing anything wrong?

**Comment by fbdesignpro** [comment]
Thank you for the report! Which environment are you using this from (Python version, environment, etc.). e.g. Sweetviz is using Pandas 1.0+, perhaps that was not a satisfied requirement?

**Comment by Leocontreas** [comment]
Hi,
I'm using Python 3.5.6

Fact is, I am able to I import sweetviz as sv, but I cannot use the library because no module appears available (i.e. .compare(), .analyze() and so on are not understood as sweetviz modules). It is really weird. Did I install the package in a non-canonical way?

**Comment by fbdesignpro** [comment]
Hi! I'm not sure that would be the cause but the minimum requirement is Python 3.6 (I have not tested below that version number). That part does likely explain the "Could not find a version that satisfies the requirement"; I know it's not always possible, but if you can upgrade to 3.6+ it might resolve the issue.

**Comment by fbdesignpro** [comment]
Actually I thought I was listing the requirements more explicitly; I will update the docs!

**Comment by Leocontreas** [comment]
Thanks for the quick reply. I tried installing sweetviz through pip in a python 3.6.5 environment and it worked out. Also, library is correctly recognised by the interpreter :)
