### ISSUE TITLE
Minor type checking issue

### ISSUE THREAD

**Issue by ai2table** [fbdesignpro/sweetviz#71]
Both analyze and compare functions accept Tuple[pd.DataFrame, str] but DataframeReport __init__ mandates a List (see below, line 54) . Lists cast to tuples automatically, so this will all work if the user passes a list [df, "some_name] but fails if they pass a tuple (df, "some_name"). Since the functionality will not work on multiple dataframes, it makes sense to recommend  a Tuple instead of a List.      

original: 

elif type(source) == list:
    if len(source) != 2:
        raise ValueError('"source" parameter should either be a string or a list of 2 elements: [dataframe, "Name"].')

recommended change:

elif type(source) == list or type(source) == tuple:
...

**Comment by fbdesignpro** [comment]
Hey @ai2table, apologies for the long delay, it's been crazy times ;)

That sounds like a nice touch, I will add it in the next revision. :)

**Comment by fbdesignpro** [comment]
@ai2table this should be integrated in the new 2.0.7 version, thank you again! :)
