### ISSUE TITLE
EmptyDataError: No columns to parse from file

### ISSUE THREAD

**Issue by ODONNRY** [fbdesignpro/sweetviz#74]
Using Sweetviz in a Streamlit application.  Using a very simple sample csv to read into a df, which pandas can read without issue.  When the sv.analyze(df) is executed it returns an error: EmptyDataError: No columns to parse from file. Sample code below:

`    elif choice == "Sweetviz":
        st.subheader("Analysis with Sweetviz")
        data_file = st.file_uploader("Upload CSV", type=['csv'])
        if data_file is not None:
            df = pd.read_csv(data_file)
            st.dataframe(df.head())
            if st.button("Generate Sweetviz Report"):
                # Normal Workflow
                report = sv.analyze(df)
                report.show_html()
                st_display_sweetviz("SWEETVIZ_REPORT.html")`

**Comment by fbdesignpro** [comment]
Hi @ODONNRY, thank you for the report. I am not too familiar with Streamlit but given some recent feedback from users using the system, I am starting to investigate and I will report here shortly!

**Comment by fbdesignpro** [comment]
Hi @ODONNRY, thanks again for the report! I finally got to to test the setup and tried in your exact code and it... actually worked!

When I hit the button, `analyze(df)` gets executed (I see the progress bar in the terminal window), then `show_html()` brings up a browser. (I commented out `st_display_sweetviz(...)` as it seems to be something you created on your side).

I did try it with the usual Titanic data set (`train.csv`), so perhaps there is something with regard to bigger files, or the data file itself (?).

If you can still look at it, I would love to hear if it works on your end with that small data set, or if it's an issue with the data itself.
