### ISSUE TITLE
Random empty body for bigger datasets

### ISSUE THREAD

**Issue by smiglidigli** [fbdesignpro/sweetviz#76]
I have a dataset that contains 3.8k columns and 300 to 900k rows. When I run the report and save to html, it randomly outputs a file with empty body (literally, <body></body> in the source). The head is filled and the file weights around 30MB. I don`t see a pattern, it may output an empty-body file during the first run, the correct file in the second and empty-body in the third.

Env: GCP, AI Platform, python 3.7
SweetViz ver: 1.1.2 and 2.0.6

code:
```
features_per_batch = 2500
batches = len(data_source.columns) // features_per_batch + (len(data_source.columns) % features_per_batch > 0)
start_inclusive = 0
end_exclusive = features_per_batch
for batch in range(batches):
    print(f'preparing batch {batch + 1}')
    report = sv.analyze(source=data_source.iloc[:, start_inclusive:end_exclusive]
                        , **{k: v for k, v in kwargs.items() if k != 'path'})
    report.show_html(kwargs['path'] + f'_{batch + 1}.html')
    start_inclusive = end_exclusive
    end_exclusive += features_per_batch
```

The output is divided into batches, because of missing features in the html after 2501 (described in another issue). kwargs contain "path" (output path) and "pairwise_analysis" set to "off".

Unfortunately, I cannot share my dataset, as it`s proprietary.

**Comment by fbdesignpro** [comment]
@smiglidigli thank you for the detailed report; I will attempt to reproduce this on my end and let you know ASAP!

**Comment by fbdesignpro** [comment]
Hello @smiglidigli, I took a look at this one as well as the other issue you reported, and although I was able to fix the other one, I'm not getting this one.

I was able to generate those big reports and noticed that those 30 MB files do take a while to open. I'm pretty sure you must have tried this, but I wonder if it's an issue with rendering or memory on the browser side, like opening a new browser would fix it etc.? If you confirm that this still occurs when opening a fresh new browser on that file (or closing the others then reopening), that is definitely mysterious.

**Comment by smiglidigli** [comment]
Thanks for checking. I noticed that might be an issue with the way how jupyterhub of the AI Platform downloads files. Some of my csv files were also incomplete. What`s interesting, though, is that none of the files was corrupted. csvs contained less rows and your htmls just didin`t contain <body> contents.
I will install 2.0.7 on Monday and will try to move the html to GCP storage and download from there instead of downloading from jupyterhub (that worked with the csv).

**Comment by smiglidigli** [comment]
I checked today and it seems the problem is not SweetViz, but the way JupyterLab downloads files on GCP (or maybe regardless of the hosting, I don`t know). When I programmaticaly uploaded the file to storage and downloaded from there using the console functionality, the file was complete. Thanks again for checking and sorry to have bothered you.
