### ISSUE TITLE
Tqdm errors while running sweetviz.compare() or analyze() in Colab

### ISSUE THREAD

**Issue by AdityaKj** [fbdesignpro/sweetviz#79]
Feature: Item_Outlet_Sales (TARGET)
[ 18%] 00:00 -> (00:03 left)

TqdmDeprecationWarning: Please use `tqdm.gui.tqdm(...)` instead of `tqdm(..., gui=True)`
---------------------------------------------------------------------------
TqdmDeprecationWarning                    Traceback (most recent call last)
<ipython-input-38-2613e0da05df> in <module>()
----> 1 comparison_report = sv.compare([train,'Train'], [test,'Test'], target_feat='Item_Outlet_Sales',feat_cfg= feature_config)
      2 comparison_report.show_notebook()

3 frames
/usr/local/lib/python3.7/dist-packages/sweetviz/sv_public.py in compare(source, compare, target_feat, feat_cfg, pairwise_analysis)
     21             pairwise_analysis: str = 'auto'):
     22     report = sweetviz.DataframeReport(source, target_feat, compare,
---> 23                                       pairwise_analysis, feat_cfg)
     24     return report
     25 

/usr/local/lib/python3.7/dist-packages/sweetviz/dataframe_report.py in __init__(self, source, target_feature_name, compare, pairwise_analysis, fc)
    199             filtered_series_names_in_source.remove(targets_found[0])
    200             target_type = self._target["type"]
--> 201             self.progress_bar.update(1)
    202 
    203         # Set final target series and sanitize targets (e.g. bool->truly bool)

/usr/local/lib/python3.7/dist-packages/tqdm/notebook.py in update(self, *args, **kwargs)
    263     def update(self, *args, **kwargs):
    264         try:
--> 265             return super(tqdm_notebook, self).update(*args, **kwargs)
    266         # NB: except ... [ as ...] breaks IPython async KeyboardInterrupt
    267         except:  # NOQA

/usr/local/lib/python3.7/dist-packages/tqdm/std.py in update(self, n)
   1203             Increment to add to the internal counter of iterations
   1204             [default: 1]. If using float, consider specifying `{n:.3f}`
-> 1205             or similar in `bar_format`, or specifying `unit_scale`.
   1206 
   1207         Returns

TqdmDeprecationWarning: Please use `tqdm.gui.tqdm(...)` instead of `tqdm(..., gui=True)`

**Comment by AdityaKj** [comment]
For NewBees using sweetviz, after install restart the colab env. and start using sweetviz.

**Comment by AdityaKj** [comment]
CLosing Issue now

**Comment by fbdesignpro** [comment]
@AdityaKj thank you for the report! It's good information if anyone else runs into this. I hope you will find the library useful!
