### ISSUE TITLE
import sweetviz doesn't work

### ISSUE THREAD

**Issue by paulineolivierMFG** [fbdesignpro/sweetviz#8]
I run the command `pip install sweetviz`. The library was successfully installed but when I run the command `import sweetviz as sv`, I have the error : `AttributeError: module 'sweetviz' has no attribute 'from_dython'`

**Comment by fbdesignpro** [comment]
Thank you for the report! That's an interesting one... this attribute would be part of the installed package. Which environment are you using? (e.g. IDE/GUI, Python version, etc.)

**Comment by paulineolivierMFG** [comment]
I work with IntelliJ IDEA (python plugin), in a conda environment and with python 3.6. I tried to uninstall and reinstall the package multiple times and it works now. Thank you

**Comment by fbdesignpro** [comment]
I'm glad it worked out! It might have been a depedency that eventually got resolved; either way thank you for the report and update!
