### ISSUE TITLE
Unable to install pip install sweetviz in anaconda below are the error messages Kindly help !!

### ISSUE THREAD

**Issue by rakeshraghavendrad** [fbdesignpro/sweetviz#84]
ERROR: Could not find a version that satisfies the requirement sweetviz (from versions: none)
ERROR: No matching distribution found for sweetviz

**Comment by fbdesignpro** [comment]
Hello @rakeshraghavendrad! A common cause for this would be some incompatibility with the Python/environment you are using. Can you say  which version of Python you are using (e.g. 3.6.1), and in which environment (e.g. PyCharm, Jupyter, etc)? Thanks!

**Comment by YASHGUPTA2611** [comment]
Hi @rakeshraghavendrad, the command for installing Sweetviz library in anaconda is " **_conda install -c conda-forge sweetviz_** ".

Another method to install Sweetviz is to go in Anaconda navigator and search for sweetviz package and install it.

Here is the anaconda page for sweetviz library - [https://anaconda.org/conda-forge/sweetviz](url)

**Comment by fbdesignpro** [comment]
@YASHGUPTA2611 it's been a while, but thank you for following up on this issue! :) Closing it now.
