### ISSUE TITLE
Possible error in the correlations plot header

### ISSUE THREAD

**Issue by DanilZherebtsov** [fbdesignpro/sweetviz#85]
<img width="850" alt="Screenshot 2021-03-22 at 12 11 44" src="https://user-images.githubusercontent.com/35999411/111966428-f700f880-8b07-11eb-8058-a70afb838f1b.png">

looks like you wanted to say 'column' here instead of 'row'

**Comment by fbdesignpro** [comment]
@DanilZherebtsov haha yeah that whole paragraph was a huge pain to word correctly, and I don't think I achieved that. ;)

Basically the cells in each row corresponds to how much the label of the row (what I call "elements on the left") provides information on the "labels at the top". So I meant "elements in the row" to be each cell in the row so it's correct that way. But they correspond to the labels listed at the top.

Haha re-reading all this, it does feel like I should mention labels in some way. I'll work on the wording some more. Let me know if that made sense and if you can find a better wording ;)

**Comment by fbdesignpro** [comment]
Hello @DanilZherebtsov after running a few tests, I have to say you're right! The wording was not clear enough but also it was flipped! Thank you for bringing this up. It is fixed in the new release.
