### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by SJDO01** [fbdesignpro/sweetviz#86]
Hi,

I am beginner on Python and i've actually discovering sweetviz. 
(this packege is wonderfull ! )

But, I trying to compare 2 conditions in my dataset and i have this message  in below :

ZeroDivisionError: float division by zero

Before to use this package i have tranform the non-numerical labels to numerical labels and clean up the NANs.

Can you help me ? 
<img width="1096" alt="Capture d’écran 2021-04-06 à 20 14 52" src="https://user-images.githubusercontent.com/75795028/113758953-caa6c800-9714-11eb-90b6-4a654d3d7102.png">

**Comment by fbdesignpro** [comment]
Hi @SJDO01 ! Thank you for the report, apologies for the slight delay. I will attempt to reproduce this and can back to you shortly.

**Comment by fbdesignpro** [comment]
(status update: busy week, hoping to get this done this week!)

**Comment by subho22** [comment]
Any update?? Faced the same issue

**Comment by fbdesignpro** [comment]
@subho22 @SJDO01 I have been kept away for a good amount of time but I finally got to this; it should be fixed by tomorrow (update coming). Thank you for reporting this!

**Comment by fbdesignpro** [comment]
@subho22 @SJDO01 should now be officially fixed in 2.1.1! Thanks again and let me know if you find anything else!
