### ISSUE TITLE
Not able to remove logo 

### ISSUE THREAD

**Issue by kirankhannas** [fbdesignpro/sweetviz#87]
import sweetviz as sv
sv.config_parser.read("Override.ini")
[Layout]
show_logo = 0

Not working it shows NameError: name 'Layout' is not defined

**Comment by fbdesignpro** [comment]
@kirankhannas thank you for the info, I would really like this to work well so I will try to help fix this for you. To start, I'm assuming the part starting at `[Layout]` is in the file Override.ini? If not, to clarify, that section is a separate file (`Override.ini`), which gets loaded by the `read` command. Let me know if this helps.

**Comment by kirankhannas** [comment]
Hi Francois,
Thank you so much. So this means i need to use anaconda prompt and say conda install override.ini. Is this correct or i have to write in jupiter notebook as read Override.ini. 

Can you send me an example of this command where you used to remove the logo.Thanks

Sincerely 
Kiran Khannas

**Comment by fbdesignpro** [comment]
Hi @kirankhannas, apologies for the delay in answering as I was not able to get to anything Sweetviz-related this week. The `Override.ini` is actually a **separate file** that contains settings you wish to override.

The `sv.config_parser.read("Override.ini")` command is the only thing you need to add to Python, and it loads that file.

So you need to make sure the path/filename you specify in the `read()` command points to such a file, and it should work!

I don't think it even needs to end with .ini; there is a limitation here I cannot upload a `.ini` file so here is an example .txt file, you should be able to simply load it using `sv.config_parser.read("Override.txt")`.

[Override.txt](https://github.com/fbdesignpro/sweetviz/files/6377347/Override.txt)

Thank you, let me know if that works!

Francois

**Comment by kirankhannas** [comment]
Thank you Francois. It works for me and fantastic work. This is amazing. Is there a way we can insert custom logo as well?
Sorry, for my late responde, because of suffering from covid.

**Comment by fbdesignpro** [comment]
@kirankhannas I hope you are feeling better :(

Thank you for the good words, I am glad it was working eventually! I am adding this to a desired feature, but unfortunately I don't think I will have the time to work on that feature in the short term. Closing the issue for now but I am keeping this on a future feature list.
