### ISSUE TITLE
How can I compare more than 2 subsets

### ISSUE THREAD

**Issue by subho22** [fbdesignpro/sweetviz#88]
How can I compare more than 2 subsets

**Comment by fbdesignpro** [comment]
Hello @subho22! Thank you for looking into this; unfortunately, right now the architecture is geared towards comparing 2 data sets or subsets (you can see from the graphical layout how everything has 2 columns, etc.). It was a design decision to favor simplicity/clarity for a core use case, but it does  mean it is not possible at this time to compare more than 2 at the same time. The only workaround is to perform multiple comparisons, although I understand this is not ideal.

**Comment by fbdesignpro** [comment]
Closing the issue as this is a fundamental design decision (from an interface and internals perspective as discussed above).
