### ISSUE TITLE
Showing integer columns as categorical and throwing error.

### ISSUE THREAD

**Issue by ajsharma22** [fbdesignpro/sweetviz#91]
If I analyze these two datasets individually,  I don't get any error and the I also get the viz of all the integer columns.
But when I try to compare these dataframe, I get the below error.

"Cannot convert series 'Web Visit' in COMPARED from its TYPE_CATEGORICAL
to the desired type TYPE_BOOL."

I also tried the FeatureConfig to skip it, but no avail.

`pid_compare = sweetviz.compare([pdf,"234_7551009"],[pdf_2,"215_220941058"])`

[both_dataFrame.zip](https://github.com/fbdesignpro/sweetviz/files/6516548/both_dataFrame.zip)

**Comment by fbdesignpro** [comment]
@ajsharma22 thank you for the report! It looks like dataFrame1 only contains 0 & 1, so it is classified as boolean so it cannot be compared against the second one which is categorical (that one has 0,1,2,3 as you probably know!).

This is an interesting case where I might be able to detect the issue and re-consider the first data set as categorical, but as you mention, the system SHOULD be able to handle it if you use FeatureConfig to force dataFrame1 to be considered CATEGORICAL.

I just tried the following and it seems to work, let me know if it helps!
```
feature_config = sweetviz.FeatureConfig(force_cat = ["Web Desktop Interaction"])
report = sweetviz.compare(df1, df2, None, feature_config)
```

**Comment by fbdesignpro** [comment]
After all this time I'll assume it worked, closing! :)
